name: Testsuite build

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/nimo-labs/nimobuild:latest 
    steps:
    - uses: actions/checkout@v2
      with:
        path: 'microNIMO-examples'
    - run: |
        cd microNIMO-examples
        ./buildall.sh
      name: Compile